version: "3.7"

services:
  swaggerui:
    container_name: users_info_swagger
    image: swaggerapi/swagger-ui
    ports:
      - "8084:8080"
    environment:
      - SWAGGER_JSON=/swagger/swagger.yml
    volumes:
      - ./../swagger:/swagger