version: "3.7"

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=users-info
      - POSTGRES_PASSWORD=users-info
      - POSTGRES_DB=users-info
    ports:
      - 5432:5432