version: "3.7"

services:
  postgres:
    container_name: users_info_postgres
    image: postgres:9.6
    environment:
      - POSTGRES_USER=users-info
      - POSTGRES_PASSWORD=users-info
      - POSTGRES_DB=users-info
    ports:
      - 5432:5432

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgres
    command: postgres:5432

  app:
    ports:
    - 8181:8181
    build: ../

  swaggerui:
    container_name: users_info_swagger
    image: swaggerapi/swagger-ui
    ports:
      - "8084:8080"
    environment:
      - SWAGGER_JSON=/swagger/swagger.yml
    volumes:
      - ./../swagger:/swagger